module.exports = {
  BinOp: require('./BinOp'),
  UnaryOp: require('./UnaryOp'),
  Num: require('./Num'),
  Assign: require('./Assign'),
  Compound: require('./Compound'),
  NoOp: require('./NoOp'),
  Var: require('./Var'),
  Block: require('./Block'),
  Program: require('./Program'),
  Type: require('./Type'),
  VariableDeclaration: require('./VariableDeclaration'),
  ProcedureDecl: require('./ProcedureDecl'),
  ProcedureInvokation: require('./ProcedureInvokation'),
  Return: require('./Return'),
};
