module.exports = {
  INTEGER: 'INTEGER',
  PLUS: 'PLUS',
  MINUS: 'MINUS',
  MULTIPLY: 'MULTIPLY',
  DIVISION: 'DIVISION',
  MODULAR: 'MODULAR',
  EOF: 'EOF',
  SPACE: ' ',
  OPENBRACE: 'OPENBRACE',
  CLOSEBRACE: 'CLOSEBRACE',
};
